sudo: required

os:
  - linux

addons:
  apt:
    packages:
      - docker-ce

git:
  depth: 4

services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag lacledeslan/gamesvr-hl2dm-freeplay --build-arg BUILDNODE=TravisCI ./linux
  - docker run -it --rm lacledeslan/gamesvr-hl2dm-freeplay ./ll-tests/gamesvr-hl2dm-freeplay.sh

notifications:
  slack:
    secure: LlQimJ2OFyxs4s3Tmwe/4HnV8LdPFxGiziNKhXEAMoFqfpaWOFcZ4KzlUJHY8eOfiR1ECkIekKNM13/qbyQwjJKFAHtnuwMrMgPYtKheH588IxOdeLghs4R0Fn3kiubAvXT5BR1qsoZ9/ueZ5tpsb2Aw4NIGjZvlNI01OjnfwQ4UIel+Q+MqxXfjZ6F1PFN6NsLn19LW++i8AUW4hSdkzR+nXFk3OVp3T33pjCSkP5Vk+wmQlC4QjrHk5gu8cHFZ93zF9HFo+C46wo0aVTOLmcjAQx08MG6OzoeH5SWGBW6kfksLCQyZ7zVQA271a2s8ifiApQKJktT9RAa9L9E0ttWcjaRNGqKe3FKQPpNEI2sY/TBK2GURTS6DBvdekbO2E1ynl07uFiLDyciBPYpcKwItvx7cJKx20sMpg50ig+P4Rmq6dqp4Gy8I8TuarC1jQ5Umj0wXi+oa4jiH0QDm2yQ0CEUCXMko+Yx2SU7yzpwHNNUDgANtXwkIn50jrgG0FDDlOCf/QVkcYK8ZL82rmLLThvaVu7lGzGre6RbP0k6YUSpGDl0YgGVE+WQRRBaAPP52zWGXmATFa42xFuXWRtCFFiGyGiLy2ivUUrrDMGm6WWN/D+G/WU3LJXqH35AWLzGPhuART/itGQJ241HxmUrz6iPvTprMve/rPVNh1aM=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-hl2dm-freeplay
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-hl2dm-freeplay/$MICROBADGER_TOKEN
